# Generated by Django 2.2.5 on 2019-09-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('A', 'Add'), ('U', 'Upgrade'), ('D', 'Downgrade'), ('V', 'Version changes'), ('R', 'Remove'), ('M', 'Modification')], max_length=1)),
                ('oldvalue', models.CharField(blank=True, max_length=255)),
                ('newvalue', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
